### ISSUE TITLE
Copying code is not easy

### ISSUE THREAD

**Issue by mkonicek** [frantic/live-coding#1]
There are two top level elements: `code`, `changes`. The element with changes contains newlines and covers the whole code area, therefore I can't select a part of the code in order to copy it.

**Comment by flipace** [comment]
my PR fixes this by adding pointer-events: none to the changes container. this way, the pointer events are passed through to the elements below.

**Comment by frantic** [comment]
https://github.com/frantic/live-coding/pull/3
